name: Publish Docker Image

on:
    push:
        branches:
            - main

jobs:
    push-to-registry:
        name: Push to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Extract meta information
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: sheikhariful/practice-github-action
            - name: Build and Push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
