# Name of the workflow
name: Run Test

# Event list
on: [push]

# Jobs
jobs:
    # Job to run tests
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node.js and pnpm
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x
                  cache: "pnpm"
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Install Dependencies
              run: pnpm install
            - name: Run tests
              run: pnpm run tests
            - run: echo "Successfully Complete All test"
